name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Pip Audit
        uses: pypa/gh-action-pip-audit@v1
        with:
          # additional options can be added here

      - name: Additional Steps
        run: echo 'Additional steps'
